server:
  port: 3333
spring:
  application:
    name: chl-crowd-redis
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000