server:
  port: 80
spring:
  application:
    name: chl-crowd-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
zuul:
  sensitive-headers: "*"
  ignored-services: "*"
  routes:
    crowd-portal:
      service-id: chl-auth
      path: /**
ribbon:
  eureka:
    enabled: false
chl-auth:
  ribbon:
    listOfServers: http://localhost:4444