server:
  port: 80
spring:
  application:
    name: chl-crowd-zuul
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
zuul:
  sensitive-headers: "*"
  ignored-services: "*"
  routes:
    crowd-portal:
      service-id: chl-auth
      path: /**
chl-auth:
  ribbon:
    listOfServers: http://localhost:4444