server:
  port: 4444
  tomcat:
    connection-timeout: 180000
spring:
  application:
    name: chl-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
short:
  message:
    method: POST
    appcode: f3c717a423ca4ec3abd25e3d805e7b67
ribbon:
  ReadTimeout: 70000
  ConnectTimeout: 70000

